/* START QUERY BUILDER */
DEFINE
MEASURE tickets[trimestre1] = SUMX(tickets,[Abril]+[Mayo]+[Junio])
MEASURE tickets[trimestre2] = SUMX(tickets,[Julio]+[Agosto]+[Septiembre]+[Octubre])
EVALUATE
SUMMARIZECOLUMNS(
    tickets[operador],
    tickets[Total],
    tickets[PVP],
    "trimestre1", [trimestre1],
    "trimestre2", [trimestre2]
)
ORDER BY 
    tickets[operador] ASC,
    tickets[PVP] ASC
/* END QUERY BUILDER */